<?php
/*
|--------------------------------------------------------------------------
| Custom API routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
| routes generated by the CRUD generate command will be outputted here.
| Remember to protect them using the auth / permission middlewares
| as necessary
|
 */
